package com.capgemini.sesp.ast.android.module.util.execute;

public enum ExecuteType {
	AST_APPLICATION_STARTED,
	BST_APPLICATION_STARTED,
	AST_TYPE_DATA_DOWNLOAD,
	AST_TYPE_DATA_DOWNLOADED,
	BST_TYPE_DATA_DOWNLOAD,
	BST_TYPE_DATA_DOWNLOADED,
	WORKORDERS_DOWNLOADED,
	DOWNLOAD_WORKORDERS
}
